### ISSUE TITLE
Select which LEDs to turn on

### ISSUE THREAD

**Issue by dhavaldesai-HA** [neilenns/node-red-contrib-wled2#105]
Dear Sir,

Is it possible to add a feature that let me select which LEDs I wanna turn on in the whole strip? For example, a strip containing 300 LEDs, I wish to turn on only first 150 LEDs and the last 150 LEDs remain off. 

I'd be thankful if you can put that in if it's not too much trouble. 

Thanks,
Dhaval

**Comment by neilenns** [comment]
This could be handled via segment support, however I looked at that in the past and it was more work to add than I'm willing to do.

You can still solve the issue by sending the correctly formatted JSON to your WLED device directly. Use an http-request node and send JSON formatted according to this documentation: https://kno.wled.ge/interfaces/json-api/
