### ISSUE TITLE
Set WLED Server IP Address through msg object

### ISSUE THREAD

**Issue by tkotz8105** [neilenns/node-red-contrib-wled2#106]
This is a great piece of node red software.  Thank you very much.  I've been using it to control 5 WLED devices.   The current capability only includes setting the WLED Server IP Address when setting up the node.  I was wondering if it might be possible to dynamically set the server ip address by setting it in the msg object such as msg.address.  I've looked at the software and didn't see an "easy" way to include this option.

**Comment by neilenns** [comment]
Thanks for the feature request! I took a look at the code and supporting this would require fundamental changes to how the node is written so alas it isn't something I'm going to tackle.

**Comment by tkotz8105** [comment]
Thanks @neilenns for the quick response.  I had a suspicion that it would require a major change.  Thanks for looking into it.
