### ISSUE TITLE
Increase/Decrease Brightness?

### ISSUE THREAD

**Issue by Andoramb** [neilenns/node-red-contrib-wled2#108]
Hey, here's a quick question:
Is it possible to increase/decrease brightness/color temp, like in a HomeAssistant node as below:
![image](https://user-images.githubusercontent.com/3399628/156057507-f002bb79-4d91-4408-84d4-dbd6b9a7ed10.png)

Thank you :)

**Comment by dougle03** [comment]
![image](https://user-images.githubusercontent.com/59865048/156118228-0875610f-5e9f-4cf7-96be-85572892a302.png)
See image. This is an example from my NodeRed

**Comment by Andoramb** [comment]
Not sure I get it.
But what I meant is to increase the brightness by 10% compared to the current value.
On the image above you input directly a max value

**Comment by neilenns** [comment]
The node doesn't support adjusting brightness by a percent. If you want to do something like that I suggest just sending JSON directly to the WLED device using the built-in HTTP and JSON nodes. The API is relatively straightforward: https://kno.wled.ge/interfaces/json-api/.
