### ISSUE TITLE
Nothing happening

### ISSUE THREAD

**Issue by scargill** [neilenns/node-red-contrib-wled2#111]
I'm suer its just me but I have a working WLED board,,, I indtslled WLED2 in Node-Red - and passed the Ip of the board, it SAYS it is connected, but in Node-Red if  I select, say, ON and effect RAINBOW, nothing happens - am I missing the point? I'm quite familiar with both Node-Red and wLED but maybe I'm just as bit slow on this ocasion as I can't see why my LEDS which will happily select an effect in the WLED webui, do nothing in Node-Red. Put me out of my misery please?

![image](https://user-images.githubusercontent.com/1889411/163970314-1fbcede8-5395-48fb-8147-4bc310f010ec.png)

![image](https://user-images.githubusercontent.com/1889411/163970412-a203bf3c-69fe-4cd8-94a0-c09552882566.png)

Alsoi am I mising the bit that sets the number of LEDS?

**Comment by neilenns** [comment]
Are you actually triggering the node? Just having it configured won't result in anything, it needs an input to actually cause the node to activate. If you are testing things out try connecting a timestamp node at the front, deploy, then click the timestamp node to trigger.

Configuring the number of LEDs should be done in the WLED web UI.

**Comment by scargill** [comment]
Wheeee... thanks. Didn't think of that. Sorted.

**Comment by neilenns** [comment]
Glad it worked!

**Comment by neilenns** [comment]
Is it not working for you @scargill ?

**Comment by scargill** [comment]
Yes, sorry I left a comment but had an Internet failure today so the comment got lost. All is working but I did want to ask if there was any way your node could accept effect names rather than numbers -  I found RAINBOW just by checking through the effects - {"effect":65} - but if it was possible to put in {"effect":"rainbow"} that would future proof against changes in WLED... or am I missing something...

**Comment by neilenns** [comment]
If you are passing JSON directly to the node you are better off bypassing my node entirely and just sending it as an HTTP request to your WLED device directly, my node adds nothing of value in that situation.

A number is what WLED expects so that's what I take and send.
