### ISSUE TITLE
Lights turn orange after deploy

### ISSUE THREAD

**Issue by jasondreher** [neilenns/node-red-contrib-wled2#114]
Whenever I deploy node-red my WLED lights turn orange and are disconnected and unreachable for a bit. Any ideay why this is? or how to debug it to see what the issue is?

I am running node red in HomeAssistant
and WLED version 0.14.0-b1

**Comment by neilenns** [comment]
Sounds like for some reason your WLED controller is resetting. The lights turning orange you can disable by going into WLED settings for that device and unchecking the option to power on the lights after restart. Not sure why the controller would reset though when you deploy node-red.
