### ISSUE TITLE
Most WLED devices crashing everytime I restart Home Assistant

### ISSUE THREAD

**Issue by 1liminal1** [neilenns/node-red-contrib-wled2#116]
Hey guys, 

Now I'm not sure if they are related, but every time I restart home assistant all my WLED devices are crashing (or the bulk of them anyway) node-red-contrib-wled2 is pretty much the only way I control my devices. But again Im not 100% sure if this is the issue. 

Has anyone else had this issue? Again its the bulk of WLED devices crashing and they wont come back till I restart them.

**Comment by neilenns** [comment]
I haven't heard any reports of this and nothing has changed in this for a long while. Are you sure you don't have another integration that might be communicating with WLED?

**Comment by 1liminal1** [comment]
Yeah ok, I just wanted to check, it seemed to start after an update of WLED, but also updated HA round the same time. And as you say, this integration has not been updated for some time. I was thinking it was maybe this integration interacting with WLED in some way that the new WLED does not like. But ill assume you're up todate and not having issues? 

SO maybe HA and WLED :( annoying, ill keep digging. 

Thanks for letting me know :)
