### ISSUE TITLE
State defaults to ON, cannot change to any other state

### ISSUE THREAD

**Issue by boldface1** [neilenns/node-red-contrib-wled2#62]
When configuring this node, the state defaults to on and doesn't save when I set it to 'off' or 'toggle'

**Comment by neilenns** [comment]
I just gave this a try and it's working fine. Can you paste a screenshot of the configured node after you've configured it and deployed?

**Comment by neilenns** [comment]
Oh wait I think I had an older version that didn't have toggle 😂 Let me update and try again.

**Comment by neilenns** [comment]
Ok I can reproduce this. Hang tight, will fix.

**Comment by neilenns** [comment]
This is fixed and published. Embarrassing mistake! Thanks for reporting it.

It takes a little bit for the node red website to update with the new version. You're looking for version `2.1.1`. Once it's available update the node. You *might* have to re-create the nodes in your flows for the change to work. Try without first, and if it's still not right then re-create the node.

**Comment by boldface1** [comment]
Cheers! Thanks for the quick fix! :)
