### ISSUE TITLE
Unable to configure brightness

### ISSUE THREAD

**Issue by benblb** [neilenns/node-red-contrib-wled2#64]
Able to configure most options including effect speed, but for some reason brightness has no effect. 

`msg.payload = {"effect": 16, "brightness": 128, "state": "on", "color1": [0, 255, 0], "color2": [200, 100, 100]};
return msg;`

Any ideas on what I might be doing wrong? I've tried very low and very high brightness values with no result.

**Comment by neilenns** [comment]
Oh geeze. It looks like I forgot the line to set the brightness 😐

I'll get a fix out later today!

**Comment by benblb** [comment]
Figured that might be it, thanks!

**Comment by neilenns** [comment]
Embarrassing issue 😂

**Comment by benblb** [comment]
Happens to everyone. This is an awesome integration that I've really been enjoying. Not judging at all!

**Comment by neilenns** [comment]
Fixed. Give it an hour or so to update on nodered.org then you can update to the latest version (2.1.2) and setting payload.brightness should work!

**Comment by neilenns** [comment]
This is now available on nodered.org.

**Comment by benblb** [comment]
Working great for me! Thanks for such a quick fix.

**Comment by neilenns** [comment]
Woot woot!!! Thanks for confirming.
