### ISSUE TITLE
Add support for RGBWW LEDs.

### ISSUE THREAD

**Issue by LL-Kool-Aid** [neilenns/node-red-contrib-wled2#66]
Cannot control just the white LED's.

**Comment by neilenns** [comment]
Do you want to set it via the UI or via the incoming `msg.payload`?

**Comment by LL-Kool-Aid** [comment]
Msg.payload would be fantastic.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by neilenns** [comment]
So I *think* it will work via the payload already. Set `payload.color1` to an array of four values with the 4th value being the W component:

```javascript
"color1": [0, 0, 0, 128]
```

Let me know if that does/doesn't work.

**Comment by LL-Kool-Aid** [comment]
That worked! Thank you very much.
________________________________

**Comment by neilenns** [comment]
Nice! Now I just have to figure out how to support it via the UI.

**Comment by neilenns** [comment]
Not gonna happen via the UI, but at least it's supported via the payload.

**Comment by Riggaa** [comment]
Hello, I understand that this issue has been closed, but is there any way that I could get a quick explanation on how to modify the msg.payload with the WLED node? I tried using the change node (before and after the WLED node) to set payload.color1 to "color1": [0, 0, 0, 128], but I didn't find any success in getting my WW LEDs to turn on. Unfortunately the online guides for changing the payload don't seem to be clicking with me today so I'm hoping that someone can point me in the correct direction on getting my WW leds to automatically turn on/off. Thanks for everything, I really appreciate the work you've done on this node making life easier for people like me.

**Comment by neilenns** [comment]
Honestly I would ignore my node entirely and just directly send the JSON that WLED expects to receive using the `http request` node. My wled2 node adds no value once you are sending payloads with JSON.

Documentation for the JSON API is at https://github.com/Aircoookie/WLED/wiki/JSON-API. If you have trouble getting it working the NodeRed forum is super helpful: https://discourse.nodered.org/

**Comment by Riggaa** [comment]
Okay that make sense. I appreciate the assistance.
