### ISSUE TITLE
Node Red Constant Errors

### ISSUE THREAD

**Issue by nytram-md** [neilenns/node-red-contrib-wled2#70]
Hi

In testing the node works well when running but I keep getting messages and error reporting on the node itself as per image.

![image](https://user-images.githubusercontent.com/55548608/94132626-75315a80-fe57-11ea-8626-1ede202846cc.png)

This is what I get when I look at Node red after a few hours.

![image](https://user-images.githubusercontent.com/55548608/94161604-c2c0be00-fe7d-11ea-8304-79face60ac3e.png)

Cheers martyn

**Comment by nytram-md** [comment]
WLED is alive and well

![image](https://user-images.githubusercontent.com/55548608/94161778-f56ab680-fe7d-11ea-94b2-d6bb8bac947e.png)

**Comment by neilenns** [comment]
I've seen this occasionally as well and unfortunately I think it's an issue with WLED's API. There's nothing special in my code: I just make a web call to the address shown in the error. That request is timing out, presumably because WLED's API isn't responding.

One thing to try next time you see this error: grab the URL shown in the error message and try dropping it into your browser and see if you get a response.

**Comment by nytram-md** [comment]
Hi

I will have a look.

If its not an actual error and works. Can you supress the error to stop it reporting ?

Thanks for quick response

Martyn


Regards

Martyn

________________________________

**Comment by nytram-md** [comment]
Just checked and all is OK with the link

![image](https://user-images.githubusercontent.com/55548608/94163470-cead7f80-fe7f-11ea-904c-f37edb833cb9.png)

**Comment by neilenns** [comment]
It is an actual error, not something I can/should suppress. When you see this error does it eventually just start working again by itself? If yes, does the node to back to showing a green state? Or does it start working but stay showing a red error?

**Comment by nytram-md** [comment]
![image](https://user-images.githubusercontent.com/55548608/94168202-4a5dfb00-fe85-11ea-839f-b918f1413adb.png)

Never seen all 4 say connected. Sometimes all say error or the top one is connected as per above.

Ill keep an eye and have a look later and let you know.

cheers

**Comment by Schocker360** [comment]
I had this error as well and it appears to happen when deploying the flow and the nodes try to connect all at once.  If I change a node and only deploy changed nodes, it works.

**Comment by blazoncek** [comment]
Too many simultaneous requests to WLED instance can deplete free memory on ESP (even ESP32). They may even cause WLED to reboot.
Try to sequence your requests.

**Comment by neilenns** [comment]
Closing old issues.
