### ISSUE TITLE
WLED does not update when multiple segments are used

### ISSUE THREAD

**Issue by daredoes** [neilenns/node-red-contrib-wled2#72]
When multiple segments are set, the current implementation will only affect segment 0, if any segment.

There is an undocumented aspect of the JSON API where instead of sending an array of objects with IDs, we can send an object without an ID to act as a master control for all segments.

This is addressed in #71

**Comment by neilenns** [comment]
Fixed, will available as v2.1.4 shortly. Thank you for the contribution!
