### ISSUE TITLE
Feature request - return WLED API XML response

### ISSUE THREAD

**Issue by TheOriginalMrWolf** [neilenns/node-red-contrib-wled2#78]
Hi,

Thanks for the useful node!

As an enhancement, could you please add the WLED API XML response to the returned msg (rather than just the msg that was received as input).

Thanks!

**Comment by neilenns** [comment]
This would be a breaking change I'm not keen to do. I think the better approach is to add a new node that simply returns the current state, as requested in #79

**Comment by TheOriginalMrWolf** [comment]
@danecreekphotography  Oh - I had thought you could just add another attribute (containing the XML) to the existing returned message (eg msg.responseXML) , which should avoid breaking anything, no?

Either way, thanks for looking at it so quickly 👍

**Comment by neilenns** [comment]
I don't think there's any point to doing this, it wouldn't offer any value over just using a web request node to query the state from the device. It's a trivial API: just web request to `http://ipaddress/json/state` and you will get the full current state back in much more detail than I'd ever expose from the node.
