### ISSUE TITLE
Change request - disable default values

### ISSUE THREAD

**Issue by TheOriginalMrWolf** [neilenns/node-red-contrib-wled2#80]
Hi there :)

It would be truly great if each of the properties of the Wled2 node were optional (ie checkbox next to each to enable/disable default values).

This would make certain use-cases a lot simpler and give a better user experience.

For instance - WLED is displaying an effect which was invoked via the WLED app.  I would like to turn this off via NR by simply setting state = off, so that we get the same UX as doing so via the app or the web interface- eg, simply fades to black.

Unfortunately, with current implementation, I can't do that.  If I send a message with only msg.payload.state = "off" then effect stops, switches to Solid effect, sets a colour, and only then turns off -- all of which is a little sub-optimal ;).  And I can't set state to be the existing state, as I have no way of knowing the current state (see issue #79).

I can get the desired result by invoking the API directly, however that defeats the purpose of having this node in the first place!

Hope that's do-able - thank you!

**Comment by neilenns** [comment]
Are there other situations where this is causing issues? Or just when setting payload to off?

**Comment by TheOriginalMrWolf** [comment]
Changing brightness, changing intensity, changing speed, changing any of the colours, and so on.

Thanks for looking at this so quickly!

**Comment by DcFamas** [comment]
Hey there,
having the same fault.
For example I want to change the brightness on my streamdeck to 50% and the color1 is red this flow will change also the color to white.

The json I use is literally

`{"brightness":128}`

would it be possible that just the brightness is changed?

Best regards :)

**Comment by neilenns** [comment]
> Hey there,
> having the same fault.
> For example I want to change the brightness on my streamdeck to 50% and the color1 is red this flow will change also the color to white.
> 
> The json I use is literally
> 
> `{"brightness":128}`
> 
> would it be possible that just the brightness is changed?
> 
> Best regards :)

For something that simple I suggest just sending the command directly to WLED with an `httprequest` node. You're already building JSON anyway, and the [JSON for the API is really straightforward](https://github.com/Aircoookie/WLED/wiki/JSON-API).

**Comment by DcFamas** [comment]
Okay, haven't known about this opportunity.
Now I use it. :) Thanks

**Comment by neilenns** [comment]
Closing old issues.
