### ISSUE TITLE
Set to preset

### ISSUE THREAD

**Issue by thelefty** [neilenns/node-red-contrib-wled2#81]
Is it possible to pull from their API the preset you want it to go to? It would be nice to be able to set a certain preset cause I use segments quite a bit and slot 16 is the only preset that determines that. I know you can set the default preset in the wled settings but it would be nice to have different presets for different holidays etc. Wondering if it's possible.

**Comment by neilenns** [comment]
I'm not sure to be honest. The documentation for WLED's JSON API doesn't say anything about presets, but they seem to not update it very often. I'll have to sniff the web UI traffic sometime and see.

**Comment by neilenns** [comment]
This is now available in version 2.3.0. You can either select the preset via the new dropdown UI or specify it via payload with `preset`. Selecting a preset will override all other settings.

Unfortunately I couldn't find a way to query the list of valid presets so the UI just shows all 16 possible slots.

**Comment by thelefty** [comment]
You're a legend. Thanks a ton!
