### ISSUE TITLE
Q: Can the output server/node be specified within the message?

### ISSUE THREAD

**Issue by dougle03** [neilenns/node-red-contrib-wled2#83]
Hi,
Can't find in the docs how to define the node server (IP) within the payload message.
Can the target node/server be defined within the incoming payload? if so, what's the syntax? 
I've spent 30 mins trying loads of variants...

Thanks

**Comment by neilenns** [comment]
It isn't possible. If you are doing that level of customization via incoming payload I suggest just directly using an HTTP Request node and calling the [WLED JSON API directly](https://github.com/Aircoookie/WLED/wiki/JSON-API).

**Comment by dougle03** [comment]
Thanks for the response.
