### ISSUE TITLE
Loosing Segments each time I deploy a change

### ISSUE THREAD

**Issue by GM-AZ** [neilenns/node-red-contrib-wled2#84]
Using node-red in Home Assistant.  Using a Input (dropdown showing the Patterns) then a switch to trigger wled2 to correct pattern.  This works great except if I make a change and have to deploy the segments are wiped out.

**Comment by neilenns** [comment]
The node doesn't know anything about segments, it always sends settings for a single segment 0. If you're using segments you'll need to take a different approach to automation, such as calling the JSON API directly using `http request` nodes.
