### ISSUE TITLE
Add control to "Preset Cycle" toggle

### ISSUE THREAD

**Issue by LucasJanin** [neilenns/node-red-contrib-wled2#85]
Thanks for your WLED Node-Red implementation!

It will be nice to have access to the "Preset Cycle" toggle. I love my led cycle with different preset but I can control anymore with Node-Red the color because WLED changes automatiquely. 

My idea is to change to white during a Zoom call. With the  "Preset Cycle" toggle, it will be possible to disable the cycle during the call and reactivated it after. 

Thanks

**Comment by daredoes** [comment]
@LucasJanin this is a great call-out with the new 0.11.0 firmware! I'll try to get this started before the end of the weekend! 

For myself for later from the JSON Docs

> pl | -1 to 0 | ID of currently set playlist. For now, this sets the preset cycle feature, -1 is off and 0 is on.

**Comment by LucasJanin** [comment]
> @LucasJanin this is a great call-out with the new 0.11.0 firmware! I'll try to get this started before the end of the weekend!

Fantastic!!! Thanks for taking my subjection into consideration :-)

**Comment by neilenns** [comment]
Closing old issues.
