### ISSUE TITLE
Manual entry of IP address

### ISSUE THREAD

**Issue by marc-gist** [neilenns/node-red-contrib-wled2#93]
I have wled on different VLAN than my node red, so need to enter in the IP address manually.
It doesn't appear to be possible.

**Comment by marc-gist** [comment]
Sorry, never mind. issue was me and my dark theme made it hard to see the IP enter and keep in there without invoking the discovery.  Once discover is invoked, you can't override; is there a way to allow manual IP after discovery has been triggered?

**Comment by neilenns** [comment]
Just hit the search button again and the dropdown will flip back to a text box for manual entry.
