### ISSUE TITLE
Request: Segment Selection

### ISSUE THREAD

**Issue by marc-gist** [neilenns/node-red-contrib-wled2#94]
This work is fantastic! Would it be possible to be able to select which segment this node would apply to (still a single segment, but instead of default to 0, once could select the ID (or manually enter in an ID until you can create a wonderful selection box :) )

Thanks!

**Comment by marc-gist** [comment]
I started the work and just made it an integer for segment selection and also setup ability to send in payload.
if you want to include, I sent a pull request.

**Comment by neilenns** [comment]
Closing old issues.

**Comment by hockeymikey** [comment]
@neilenns Is this issue resolved though?
